version: "3.9"

services:
  frontend:
    image: nlp-frontend
    restart: always
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: "develop-stage"
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: /bin/sh -c "yarn && quasar dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
